"""add_analysis_history

Revision ID: 0aa8f7724980
Revises: 7fd85e8507f1
Create Date: 2025-11-06 08:38:17.639752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa8f7724980'
down_revision = '7fd85e8507f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###