"""add_notifications

Revision ID: 104afa8ebb3d
Revises: e461691172ad
Create Date: 2026-03-28 12:43:31.447828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '104afa8ebb3d'
down_revision = 'e461691172ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_choices_id'), table_name='user_choices')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_selected_products_id'), table_name='selected_products')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('ORDER_STATUS', 'NEW_PROMOTION', 'PROMOTION_UPDATE', 'ORDER_CREATED', 'ORDER_CANCELLED', 'SYSTEM', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('selected_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_choice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('selected_products_product_id_fkey')),
    sa.ForeignKeyConstraint(['user_choice_id'], ['user_choices.id'], name=op.f('selected_products_user_choice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('selected_products_pkey'))
    )
    op.create_index(op.f('ix_selected_products_id'), 'selected_products', ['id'], unique=False)
    op.create_table('analysis_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detected_dish', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('alternatives_found', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('analysis_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_history_pkey'))
    )
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.create_table('user_choices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_history.id'], name=op.f('user_choices_analysis_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_choices_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_choices_pkey'))
    )
    op.create_index(op.f('ix_user_choices_id'), 'user_choices', ['id'], unique=False)
    # ### end Alembic commands ###