"""add_new_tags_structure

Revision ID: 30ab7a4642de
Revises: a6fe06d73a37
Create Date: 2025-11-04 10:09:11.467529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ab7a4642de'
down_revision = 'a6fe06d73a37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_tags_product_id'), table_name='product_tags')
    op.drop_index(op.f('ix_product_tags_tag'), table_name='product_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_tags_tag'), 'product_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_product_tags_product_id'), 'product_tags', ['product_id'], unique=False)
    # ### end Alembic commands ###