"""migrate_to_new_tags_structure

Revision ID: 7fd85e8507f1
Revises: 1e250d683337
Create Date: 2025-11-05 13:50:59.375320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd85e8507f1'
down_revision = '1e250d683337'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.add_column('product_tags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_product_tag', 'product_tags', ['product_id', 'tag_id'])
    op.create_foreign_key(None, 'product_tags', 'tags', ['tag_id'], ['id'])
    op.drop_column('product_tags', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tags', sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_tags', type_='foreignkey')
    op.drop_constraint('uq_product_tag', 'product_tags', type_='unique')
    op.drop_column('product_tags', 'created_at')
    op.drop_column('product_tags', 'tag_id')
    # ### end Alembic commands ###