"""Add tags and product_tags table

Revision ID: 8ae7d041394f
Revises: 4050d5e53dc0
Create Date: 2025-12-27 15:27:42.199168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ae7d041394f'
down_revision = '4050d5e53dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_image_hash'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('detected_dish', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('alternatives_found', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('analysis_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_history_pkey'))
    )
    op.create_index(op.f('ix_analysis_history_image_hash'), 'analysis_history', ['image_hash'], unique=False)
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    # ### end Alembic commands ###